In [1]:
%pip install ultralytics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 21.2 MB/s eta 0:00:00


In [2]:
import ultralytics
ultralytics.checks()

Ultralytics 8.4.41 🚀 Python-3.12.13 torch-2.10.0+cpu CPU (Intel Xeon CPU @ 2.20GHz)
Ultralytics 8.4.41 🚀 Python-3.12.13 torch-2.10.0+cpu CPU (Intel Xeon CPU @ 2.20GHz)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 20.6/107.7 GB disk)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 20.6/107.7 GB disk)


In [3]:
import cv2
from google.colab.patches import cv2_imshow

def show_image(image_path):
  image = cv2.imread(image_path)
  if image is None:
    print("Error : Image not Found!")
    return

  cv2_imshow(image)

In [4]:
# Run inference on an image with YOLO11n
!yolo predict model=yolo11n.pt source="https://images.pexels.com/photos/13872248/pexels-photo-13872248.jpeg"

Ultralytics 8.4.41 🚀 Python-3.12.13 torch-2.10.0+cpu CPU (Intel Xeon CPU @ 2.20GHz)
Ultralytics 8.4.41 🚀 Python-3.12.13 torch-2.10.0+cpu CPU (Intel Xeon CPU @ 2.20GHz)
YOLO11n summary (fused): 100 layers, 2,616,248 parameters, 0 gradients, 6.5 GFLOPs

WARNING ⚠️ Download failure, retrying 1/3 https://images.pexels.com/photos/13872248/pexels-photo-13872248.jpeg... HTTP Error 403: Forbidden
YOLO11n summary (fused): 100 layers, 2,616,248 parameters, 0 gradients, 6.5 GFLOPs

WARNING ⚠️ Download failure, retrying 1/3 https://images.pexels.com/photos/13872248/pexels-photo-13872248.jpeg... HTTP Error 403: Forbidden
######################################################################## 100.0%
######################################################################## 100.0%
image 1/1 /content/pexels-photo-13872248.jpeg: 448x640 6 persons, 177.2ms
Speed: 16.9ms preprocess, 177.2ms inference, 43.2ms postprocess per image at shape (1, 3, 448, 640)
Results saved to /content/runs/detect/predict
💡 Le

In [5]:
show_image("/content/runs/detect/predict/pexels-photo-13872248.jpg")

Output hidden; open in https://colab.research.google.com to view.

In [6]:
!yolo predict model=yolo26n source="/content/pexels-photo-13872248.jpeg"

Ultralytics 8.4.41 🚀 Python-3.12.13 torch-2.10.0+cpu CPU (Intel Xeon CPU @ 2.20GHz)
YOLO26n summary (fused): 122 layers, 2,408,932 parameters, 0 gradients, 5.4 GFLOPs

image 1/1 /content/pexels-photo-13872248.jpeg: 448x640 6 persons, 182.2ms
Speed: 4.8ms preprocess, 182.2ms inference, 0.5ms postprocess per image at shape (1, 3, 448, 640)
Results saved to /content/runs/detect/predict-2
💡 Learn more at https://docs.ultralytics.com/modes/predict


In [7]:
# Running inference on yolo 26n
show_image("/content/runs/detect/predict-2/pexels-photo-13872248.jpg")

Output hidden; open in https://colab.research.google.com to view.

Showing its use with python

In [8]:
from ultralytics import YOLO
model = YOLO("yolo26s.pt") #loading an official

In [9]:
# Predicting with the model
results = model("/content/pexels-photo-13872248.jpeg")


image 1/1 /content/pexels-photo-13872248.jpeg: 448x640 6 persons, 562.1ms
Speed: 5.5ms preprocess, 562.1ms inference, 0.4ms postprocess per image at shape (1, 3, 448, 640)


In [10]:
# Access the results
for i , result in enumerate(results):
  print(f"\nResult {i+1}:")

  xywh = result.boxes.xywh # center-x , center-y , width , height
  print("Bounding Box (xywh)")
  print(xywh)

  xywhn = result.boxes.xywhn # normalised xywh
  print("Bounding Box (xywhn)")
  print(xywhn)

  xyxy = result.boxes.xyxy
  print("Bounding Boxes (xyxy)") # top left x,  top left y , bottom right x , bottom right y
  print(xyxy)

  xyxyn = result.boxes.xyxyn
  print("Normalized Bounding Boxes (xyxyn) : ")  # normalized
  print(xyxyn)

  names = [result.names[cls.item()] for cls in result.boxes.cls.int()]
  print(f"Class Names \n {names}")

  confidence = result.boxes.conf # confidence score of each boxes
  print(f"Confidence Scores : {confidence}")



Result 1:
Bounding Box (xywh)
tensor([[ 828.2620, 2852.9021, 1533.1691, 2561.0933],
        [2707.6802, 2799.9338, 1318.4373, 2673.7388],
        [5369.7021, 2651.5781, 1383.1519, 2947.6797],
        [4266.3901, 2846.1816,  982.5286, 2578.2959],
        [3403.1235, 2786.8772,  965.9827, 2688.6489],
        [1735.5304, 2986.3521,  768.5378, 2306.4124]])
Bounding Box (xywhn)
tensor([[0.1327, 0.6858, 0.2457, 0.6156],
        [0.4339, 0.6731, 0.2113, 0.6427],
        [0.8605, 0.6374, 0.2217, 0.7086],
        [0.6837, 0.6842, 0.1575, 0.6198],
        [0.5454, 0.6699, 0.1548, 0.6463],
        [0.2781, 0.7179, 0.1232, 0.5544]])
Bounding Boxes (xyxy)
tensor([[  61.6775, 1572.3553, 1594.8466, 4133.4487],
        [2048.4614, 1463.0645, 3366.8987, 4136.8032],
        [4678.1265, 1177.7384, 6061.2783, 4125.4180],
        [3775.1257, 1557.0337, 4757.6543, 4135.3296],
        [2920.1323, 1442.5527, 3886.1150, 4131.2017],
        [1351.2615, 1833.1458, 2119.7993, 4139.5581]])
Normalized Bounding Box

In [11]:
for i , result in enumerate(results):
  print(f"\n\n {i+1}")
  print(f"\n{result.boxes}")
  print(f"\n{result}")




 1

ultralytics.engine.results.Boxes object with attributes:

cls: tensor([0., 0., 0., 0., 0., 0.])
conf: tensor([0.9574, 0.9564, 0.9439, 0.9326, 0.9111, 0.8750])
data: tensor([[6.1677e+01, 1.5724e+03, 1.5948e+03, 4.1334e+03, 9.5741e-01, 0.0000e+00],
        [2.0485e+03, 1.4631e+03, 3.3669e+03, 4.1368e+03, 9.5644e-01, 0.0000e+00],
        [4.6781e+03, 1.1777e+03, 6.0613e+03, 4.1254e+03, 9.4391e-01, 0.0000e+00],
        [3.7751e+03, 1.5570e+03, 4.7577e+03, 4.1353e+03, 9.3265e-01, 0.0000e+00],
        [2.9201e+03, 1.4426e+03, 3.8861e+03, 4.1312e+03, 9.1106e-01, 0.0000e+00],
        [1.3513e+03, 1.8331e+03, 2.1198e+03, 4.1396e+03, 8.7497e-01, 0.0000e+00]])
id: None
is_track: False
orig_shape: (4160, 6240)
shape: torch.Size([6, 6])
xywh: tensor([[ 828.2620, 2852.9021, 1533.1691, 2561.0933],
        [2707.6802, 2799.9338, 1318.4373, 2673.7388],
        [5369.7021, 2651.5781, 1383.1519, 2947.6797],
        [4266.3901, 2846.1816,  982.5286, 2578.2959],
        [3403.1235, 2786.8772,  965.98

In [13]:
model.save()